version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:14.2-alpine
    env_file:
        - .env
    ports:
        - "5432:5432"
    networks:
        - app
  app:
    container_name: app
    build:
        context: ./app
        dockerfile: ./Dockerfile
    ports:
        - "8080:8080"
    networks:
        - app

networks:
  app:
    driver: bridge
